### ISSUE TITLE
Aprovisionamento do GCP

### ISSUE THREAD

**Issue by smccms** [isel-leic-daw/1819v-public#3]
@pmhsfelix verifiquei que não ficou aprovisionado um projecto de GCP para o grupo S1819V-LI61N-G13. Quando é que este estará disponível? Obrigada

**Comment by pmhsfelix** [comment]
Bom dia. O projecto S1819V-LI61N-G13 já foi aprovisionado e o acesso foi concedido a 35438 e a 39304. Por favor verifiquem convite enviado para o email do IPL.
